[theme]
primaryColor = "#4CAF50"  # Green
backgroundColor = "#282C34"  # Dark background
secondaryBackgroundColor = "#FFC619"  # Slightly lighter background
textColor = "#FFFFFF"  # White text
font = "sans serif"  # Monospace font
